{
	"version": 1654710213,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/tilemapquebravel.png",
		"images/aahumberto-sheet0.png",
		"images/aalava-sheet0.png",
		"images/aamonstro-sheet0.png",
		"images/aasensor-sheet0.png",
		"images/aaalvo-sheet0.png",
		"images/fundoinicio-sheet0.png",
		"images/zzbotãoplay-sheet0.png",
		"images/creditos-sheet0.png",
		"images/imageasset-sheet0.png",
		"images/gameover-sheet0.png",
		"images/zzmenu-sheet0.png",
		"images/aadiamante-sheet0.png",
		"images/tiledbackground2.png",
		"images/fundofinal.png",
		"images/finalfundohumberto-sheet0.png",
		"images/minecart-sheet0.png",
		"images/aaavisominecart-sheet0.png",
		"media/fly.m4a",
		"media/fly.ogg",
		"media/naruto.m4a",
		"media/naruto.ogg",
		"media/whatsapp audio 2022-06-08 at 13.02.05 (online-audio-converter.com).m4a",
		"media/whatsapp audio 2022-06-08 at 13.02.05 (online-audio-converter.com).ogg",
		"media/vitoria.m4a",
		"media/vitoria.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}